name=input("enter your name:")
age=int(input("enter your age:"))
college=input("enter your college:")
print("-------Student Details-------")
print("Name:",name)
print("Age:",age)
print("College:",college)